// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwecbzmYIxLanrkBJND9B7k2-46ifnUXk',
    appId: '1:1045084828262:android:892b693c0b4c4f437d73a7',
    messagingSenderId: '1045084828262',
    projectId: 'agri-db-5dbc5',
    storageBucket: 'agri-db-5dbc5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBakd4DKBcgP1rVeDnn2zCWz9axy3HpdPo',
    appId: '1:1045084828262:web:37471eb30c9af42c7d73a7',
    messagingSenderId: '1045084828262',
    projectId: 'agri-db-5dbc5',
    authDomain: 'agri-db-5dbc5.firebaseapp.com',
    storageBucket: 'agri-db-5dbc5.firebasestorage.app',
    measurementId: 'G-SQPNV149HW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGiqM8pIS2okcl2lCPTlK8Vy0tMSDfq0Y',
    appId: '1:1045084828262:ios:f4d3f7b858de78917d73a7',
    messagingSenderId: '1045084828262',
    projectId: 'agri-db-5dbc5',
    storageBucket: 'agri-db-5dbc5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGiqM8pIS2okcl2lCPTlK8Vy0tMSDfq0Y',
    appId: '1:1045084828262:ios:f4d3f7b858de78917d73a7',
    messagingSenderId: '1045084828262',
    projectId: 'agri-db-5dbc5',
    storageBucket: 'agri-db-5dbc5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBakd4DKBcgP1rVeDnn2zCWz9axy3HpdPo',
    appId: '1:1045084828262:web:3db66d66ea417e7b7d73a7',
    messagingSenderId: '1045084828262',
    projectId: 'agri-db-5dbc5',
    authDomain: 'agri-db-5dbc5.firebaseapp.com',
    storageBucket: 'agri-db-5dbc5.firebasestorage.app',
    measurementId: 'G-7WTBDW78WR',
  );

}