// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFi_l1wZ2bb8xOs3n1xGNtWjcM_cCzf9s',
    appId: '1:541359313358:android:22113c862c905d11951b9f',
    messagingSenderId: '541359313358',
    projectId: 'es-agri-farms',
    storageBucket: 'es-agri-farms.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtM1qW58FnskykmnxA5_SSuUS3RpSOj8',
    appId: '1:541359313358:web:eb5ebb3f7b09d7cf951b9f',
    messagingSenderId: '541359313358',
    projectId: 'es-agri-farms',
    authDomain: 'es-agri-farms.firebaseapp.com',
    storageBucket: 'es-agri-farms.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOfXfYgebg2TpKI66jnmJ3BMt0_8t_Wkc',
    appId: '1:541359313358:ios:6f0acab89d81494f951b9f',
    messagingSenderId: '541359313358',
    projectId: 'es-agri-farms',
    storageBucket: 'es-agri-farms.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOfXfYgebg2TpKI66jnmJ3BMt0_8t_Wkc',
    appId: '1:541359313358:ios:6f0acab89d81494f951b9f',
    messagingSenderId: '541359313358',
    projectId: 'es-agri-farms',
    storageBucket: 'es-agri-farms.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtM1qW58FnskykmnxA5_SSuUS3RpSOj8',
    appId: '1:541359313358:web:5c79c537b4451227951b9f',
    messagingSenderId: '541359313358',
    projectId: 'es-agri-farms',
    authDomain: 'es-agri-farms.firebaseapp.com',
    storageBucket: 'es-agri-farms.firebasestorage.app',
  );

}