// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXRAFO1B0UitneRMxxqNf9W0g2BAAvB0',
    appId: '1:1051869861765:android:50e38796bbed98eb6c56ec',
    messagingSenderId: '1051869861765',
    projectId: 'agri-farms-db',
    storageBucket: 'agri-farms-db.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3-HFVp7GhgyLo6lgXZx441SWze4ZXQY',
    appId: '1:1051869861765:web:7dc29a47a58a67576c56ec',
    messagingSenderId: '1051869861765',
    projectId: 'agri-farms-db',
    authDomain: 'agri-farms-db.firebaseapp.com',
    storageBucket: 'agri-farms-db.firebasestorage.app',
    measurementId: 'G-EE2JP61L00',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD50-rqyhw4lsrNsy6_7kMhgW3lYGLBCoo',
    appId: '1:1051869861765:ios:1a9e96091dd8e9126c56ec',
    messagingSenderId: '1051869861765',
    projectId: 'agri-farms-db',
    storageBucket: 'agri-farms-db.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50-rqyhw4lsrNsy6_7kMhgW3lYGLBCoo',
    appId: '1:1051869861765:ios:1a9e96091dd8e9126c56ec',
    messagingSenderId: '1051869861765',
    projectId: 'agri-farms-db',
    storageBucket: 'agri-farms-db.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN3-HFVp7GhgyLo6lgXZx441SWze4ZXQY',
    appId: '1:1051869861765:web:7608558c455706746c56ec',
    messagingSenderId: '1051869861765',
    projectId: 'agri-farms-db',
    authDomain: 'agri-farms-db.firebaseapp.com',
    storageBucket: 'agri-farms-db.firebasestorage.app',
    measurementId: 'G-E2MXLZ91MK',
  );

}